### ISSUE TITLE
It's missing the target disk image.

### ISSUE THREAD

**Issue by smchughinfo** [PacktPublishing/Mastering-Metasploit-Third-Edition#1]
I don't know where else to put this.

Please tell me the target disk image you are using is available. How are you supposed to follow along with the book without that image? I got to page 37 before metasploitable stopped working with the book.

In the book the target gives a 302 for /phpcollab but metasploitable does not. This makes the book potentially worthless. I don't know if in ten or twenty pages if I'm going to find out this book won't work because there is no disk image to follow along with and then have to start all over again with a different book.

Can you please include the disk image, or some way to get the disk image, in this repository.

**Comment by nipunjaswal** [comment]
Hi, You are talking about phpcollab which is a web application and can be installed on any operating system. you will see that you have direct link to the installer files and all you need in phpcollab is to unzip the phpcollab to apache folder.
